### ISSUE TITLE
Problem with the sampling Drift variance

### ISSUE THREAD

**Issue by nal10** [pillowlab/StepRampMCMC#1]
Hi

while running rampfittingmodel.m I am continually getting 

Warning: Unknown problem with sampling drift variance (most likely numerical error). Keeping previous sample. 

And the gamma mean quickly shoots up to around 2*10^100. I noticed there has been fixes to this function relating to a warning message, yet the function I am running has all of the updates. Is this an issue that could be fixed with changes to the priors?

Thanks

**Comment by latimerk** [comment]
Hi,
I have also encountered this in simulations with data that could not constrain the drift variance properly. As you suggested, changing the prior seemed to fix this. Here are some values that worked for me:

params.rampPrior.w2_shape = 2;
params.rampPrior.w2_scale = 0.0025; 

best,
Kenneth

**Comment by nal10** [comment]
Hi Kenneth,

Changing those parameters has fixed the gamma mean issue, but I am still getting 

Warning: Unknown problem with sampling drift variance (most likely numerical error). Keeping previous sample.

The real issue now is this keeps the variance, w2, from ever updating from 0.0050. Any thoughts?

**Comment by latimerk** [comment]
I'm afraid I haven't run into this issue with my own tests, and I don't have any information about the data structure you are trying to fit. 
The only suggestion I can give right now is to check and make sure your timeSeries data structure is initialized correctly. The simulateRampingModel.m function generates a correctly formatted timeSeries structure.

Make absolutely certain the timeSeries.trCoh values take integer values starting at 1. (Just in case, try not to have gaps in the numbering; typing unique(timeSeries.trCoh) should give a continuous range of integer values.)
Also check the timeSeries.trialStart values.
What do the drift rate (beta) samples look like?

**Comment by nal10** [comment]
So all of this is occurring when I run either the example script with simulateRampingModel.m or simulateSteppingModel.m. 

The beta samples all fluctuate between -0.011 and -0.011.

I have been able to fix the problem using MATLAB mexcuda function rather than compileAllMexFile.m (I'm running R2016a). Just wondering what is the usual run time for using the exampleScript.m to test the programs? I am running this on

16 GB RAM
NVIDIA GeForce GTX 780M 4096 MB

 Thanks for the help.

**Comment by latimerk** [comment]
Thanks for sending your GPU type! I hadn't thought about that, but I think it tells me what the problem was. The GTX 780M has compute capability 3.0 while the compileAllMexFile.m was compiling for 3.5 by default (I've changed this argument in compileCUDAmex.m from "sm_35" to a default setting of "sm_30" to work with iMacs using that card). You'd think CUDA would throw an error in this case, but sometimes it'll just not run the CUDA kernels without saying anything.
mexcuda automatically detects this version, but I wrote this long before R2015B introduced that functionality.

Running these scripts takes several hours - I don't remember exactly how long because it's dependent the amount of data. I haven't run this on a mobile GTX card, but it could be significantly slower than the card I'm using. It has slow double precision floating point capability.
